# Generated by Django 3.1.3 on 2020-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prohibited',
            name='credential_type',
            field=models.CharField(choices=[(1, 'ip'), (2, 'domain')], default='test ip', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prohibited',
            name='credential',
            field=models.CharField(max_length=200, unique=True, verbose_name='ip or domain'),
        ),
    ]
