# Generated by Django 3.1.3 on 2020-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0002_auto_20201130_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=100, verbose_name='client ip')),
                ('credential_type', models.CharField(choices=[(1, 'ip'), (2, 'domain')], max_length=10)),
                ('credential', models.CharField(max_length=200, verbose_name='ip or domain')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
    ]
