# Generated by Django 3.1.3 on 2020-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client_email',
            field=models.EmailField(default='test@email.com', max_length=100, verbose_name='client email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='client_ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='client ip'),
        ),
    ]
