# Generated by Django 3.1.3 on 2020-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0004_auto_20201201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(1, 'confirmed'), (2, 'rejected'), (3, 'verifying')], default=3, max_length=100, verbose_name='status'),
            preserve_default=False,
        ),
    ]
