# Generated by Django 3.1.3 on 2020-12-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0005_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohibited',
            name='credential',
            field=models.IntegerField(max_length=200, unique=True, verbose_name='ip or domain'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'confirmed'), (2, 'rejected'), (3, 'verifying')], max_length=100, verbose_name='status'),
        ),
    ]
