# Generated by Django 3.1.3 on 2020-12-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0006_auto_20201201_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohibited',
            name='credential',
            field=models.CharField(max_length=200, unique=True, verbose_name='ip or domain'),
        ),
        migrations.AlterField(
            model_name='prohibited',
            name='credential_type',
            field=models.IntegerField(choices=[(1, 'ip'), (2, 'domain')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'confirmed'), (2, 'rejected'), (3, 'verifying')], verbose_name='status'),
        ),
    ]
