# Generated by Django 3.1.3 on 2020-12-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbidden', '0007_auto_20201201_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohibited',
            name='credential_type',
            field=models.IntegerField(choices=[(1, 'ip'), (2, 'domain')], verbose_name='ip/domain'),
        ),
        migrations.AlterField(
            model_name='request',
            name='credential_type',
            field=models.IntegerField(choices=[(1, 'ip'), (2, 'domain')], verbose_name='ip/domain'),
        ),
    ]
